# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '极光推送' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 极光推送

   pod 'JPush'
   pod 'XKNotificationCenter'


  target '极光推送Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '极光推送UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
